# Generated by Django 4.1.4 on 2024-07-17 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_Servicios', '0002_alter_servicio_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='imagen',
            field=models.ImageField(upload_to='media/A_Servicios'),
        ),
    ]
